version: '3.3'
services:
  frontend:
    container_name: sr_frontend_app
    build:
      context: ../patronage21-java-student-record-FE/

  backend:
    container_name: sr_backend_app
    build:
      context: .
    depends_on:
      - "postgres"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://sr_patronative_db:5432/patronative

  postgres:
    image: postgres:13.3-alpine
    container_name: sr_patronative_db
    ports:
      - 5102:5432
    volumes:
      - sr_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p4tron4tiv3
      POSTGRES_DB: patronative

  revproxy:
    image: nginx:latest
    container_name: sr_revproxy
    ports:
      - 90:80
    depends_on:
      - frontend
      - backend
    volumes:
      - ./src/main/resources/nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  sr_pgdata:
