SET search_path TO student_record;

DELETE FROM user_stage;
DELETE FROM stage;
DELETE FROM student_record.user;

INSERT INTO student_record.user(id, login, first_name, last_name, image, status_id) VALUES(NEXTVAL('user_seq'), 'janio123', 'Jan', 'Kowalski', null, (SELECT id FROM status WHERE name = 'ACTIVE'));
INSERT INTO student_record.user(id, login, first_name, last_name, image, status_id) VALUES(NEXTVAL('user_seq'), 'Lightforgee', 'Luiza', 'Tomaszewska', null, (SELECT id FROM status WHERE name = 'ACTIVE'));
INSERT INTO student_record.user(id, login, first_name, last_name, image, status_id) VALUES(NEXTVAL('user_seq'), 'znowak', 'Zdzisława', 'Nowakowska', null, (SELECT id FROM status WHERE name = 'INACTIVE'));
INSERT INTO student_record.user(id, login, first_name, last_name, image, status_id) VALUES(NEXTVAL('user_seq'), 'anowak', 'Anna', 'Nowak', null, (SELECT id FROM status WHERE name = 'ACTIVE'));
INSERT INTO student_record.user(id, login, first_name, last_name, image, status_id) VALUES(NEXTVAL('user_seq'), 'cmarek', 'Marek', 'Ćma', null, (SELECT id FROM status WHERE name = 'ACTIVE'));
INSERT INTO student_record.user(id, login, first_name, last_name, image, status_id) VALUES(NEXTVAL('user_seq'), 'tomprob', 'Tomasz', 'Problem', null, (SELECT id FROM status WHERE name = 'ACTIVE'));
INSERT INTO student_record.user(id, login, first_name, last_name, image, status_id) VALUES(NEXTVAL('user_seq'), 'czmaj', 'Czesława', 'Majewska', null, (SELECT id FROM status WHERE name = 'ACTIVE'));
INSERT INTO student_record.user(id, login, first_name, last_name, image, status_id) VALUES(NEXTVAL('user_seq'), 'serwerus', 'Sewerus', 'Sznejk', null, (SELECT id FROM status WHERE name = 'INACTIVE'));
INSERT INTO student_record.user(id, login, first_name, last_name, image, status_id) VALUES(NEXTVAL('user_seq'), 'gdudek', 'Genowefa', 'Dudek', null, (SELECT id FROM status WHERE name = 'ACTIVE'));
INSERT INTO student_record.user(id, login, first_name, last_name, image, status_id) VALUES(NEXTVAL('user_seq'), 'waletyna', 'Walentyna', 'Kwiatkowska', null, (SELECT id FROM status WHERE name = 'INACTIVE'));
INSERT INTO student_record.user(id, login, first_name, last_name, image, status_id) VALUES(NEXTVAL('user_seq'), 'jsina', 'Arkadiusz', 'Jasiński', null, (SELECT id FROM status WHERE name = 'INACTIVE'));
INSERT INTO student_record.user(id, login, first_name, last_name, image, status_id) VALUES(NEXTVAL('user_seq'), 'emeryt', 'Emeryk', 'Tarnowski', null, (SELECT id FROM status WHERE name = 'ACTIVE'));
INSERT INTO student_record.user(id, login, first_name, last_name, image, status_id) VALUES(NEXTVAL('user_seq'), 'pawlowska1', 'Judyta', 'Pawłowska', null, (SELECT id FROM status WHERE name = 'ACTIVE'));

INSERT INTO stage(id, name, description, year, technology_group_id) VALUES(NEXTVAL('user_seq'), 'Etap I', 'Etap pierwszy patronatu 2021 Mobile (Android).', 2021, (SELECT id FROM technology_group WHERE name = 'Mobile (Android)'));
INSERT INTO stage(id, name, description, year, technology_group_id) VALUES(NEXTVAL('user_seq'), 'Etap II', 'Etap drugi patronatu 2021 Mobile (Android).', 2021, (SELECT id FROM technology_group WHERE name = 'Mobile (Android)'));
INSERT INTO stage(id, name, description, year, technology_group_id) VALUES(NEXTVAL('user_seq'), 'Etap I', 'Etap pierwszy patronatu 2021 Java.', 2021, (SELECT id FROM technology_group WHERE name = 'Java'));
INSERT INTO stage(id, name, description, year, technology_group_id) VALUES(NEXTVAL('user_seq'), 'Etap II', 'Etap drugi patronatu 2021 Java.', 2021, (SELECT id FROM technology_group WHERE name = 'Java'));
INSERT INTO stage(id, name, description, year, technology_group_id) VALUES(NEXTVAL('user_seq'), 'Etap III', 'Etap trzeci patronatu 2021 Java.', 2021, (SELECT id FROM technology_group WHERE name = 'Java'));
INSERT INTO stage(id, name, description, year, technology_group_id) VALUES(NEXTVAL('user_seq'), 'Etap I', 'Etap pierwszy patronatu 2021 JavaScript.', 2021, (SELECT id FROM technology_group WHERE name = 'JavaScript'));
INSERT INTO stage(id, name, description, year, technology_group_id) VALUES(NEXTVAL('user_seq'), 'Etap II', 'Etap drugi patronatu 2021 JavaScript.', 2021, (SELECT id FROM technology_group WHERE name = 'JavaScript'));
INSERT INTO stage(id, name, description, year, technology_group_id) VALUES(NEXTVAL('user_seq'), 'Etap III', 'Etap trzeci patronatu 2021 JavaScript.', 2021, (SELECT id FROM technology_group WHERE name = 'JavaScript'));
INSERT INTO stage(id, name, description, year, technology_group_id) VALUES(NEXTVAL('user_seq'), 'Etap I', 'Etap pierwszy patronatu 2021 QA.', 2021, (SELECT id FROM technology_group WHERE name = 'QA'));
INSERT INTO stage(id, name, description, year, technology_group_id) VALUES(NEXTVAL('user_seq'), 'Etap II', 'Etap drugi patronatu 2021 QA.', 2021, (SELECT id FROM technology_group WHERE name = 'QA'));

INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'janio123'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'JavaScript')), 5, 'Wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'janio123'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'JavaScript')), 3, 'Nie wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'janio123'), (SELECT id FROM stage WHERE name = 'Etap III' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'JavaScript')), 0, 'Nie oddał zadania.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'janio123'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'QA')), 5, 'Wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'janio123'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'QA')), 3, 'Nie wszystko wykonane poprawnie.');

INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'Lightforgee'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Java')), 5, 'Wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'Lightforgee'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Java')), 3, 'Nie wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'Lightforgee'), (SELECT id FROM stage WHERE name = 'Etap III' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Java')), 0, 'Nie oddał zadania.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'Lightforgee'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Mobile (Android)')), 0, 'Nie oddał zadania.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'Lightforgee'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Mobile (Android)')), null, 'Jeszcze robi.');

INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'znowak'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'QA')), 4, 'Prawie wszystko wykonane poprawnie. Kod nie został prawidłowo sformatowany');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'znowak'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'QA')), 3, 'Nie wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'znowak'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Mobile (Android)')), 0, 'Nie oddał zadania.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'znowak'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Mobile (Android)')), null, 'Jeszcze robi.');

INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'anowak'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'JavaScript')), 5, 'Wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'anowak'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'JavaScript')), 3, 'Nie wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'anowak'), (SELECT id FROM stage WHERE name = 'Etap III' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'JavaScript')), 0, 'Nie oddał zadania.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'anowak'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Java')), 5, 'Wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'anowak'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Java')), 3, 'Nie wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'anowak'), (SELECT id FROM stage WHERE name = 'Etap III' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Java')), null, 'Jeszcze robi.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'anowak'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'QA')), 5, 'Wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'anowak'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'QA')), 3, 'Nie wszystko wykonane poprawnie.');

INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'cmarek'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'JavaScript')), 2, 'Tylko połowa punktów z zadania została zrealizowana');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'cmarek'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'JavaScript')), 3, 'Nie wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'cmarek'), (SELECT id FROM stage WHERE name = 'Etap III' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'JavaScript')), 0, 'Nie oddał zadania.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'cmarek'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Mobile (Android)')), 0, 'Nie oddał zadania.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'cmarek'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Mobile (Android)')), null, 'Jeszcze robi.');

INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'tomprob'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'QA')), 4, 'Prawie wszystko wykonane poprawnie. Kod nie został prawidłowo sformatowany');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'tomprob'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'QA')), 3, 'Nie wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'tomprob'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Mobile (Android)')), 0, 'Nie oddał zadania.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'tomprob'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Mobile (Android)')), null, 'Jeszcze robi.');

INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'czmaj'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'QA')), 1, 'Zadanie rozpoczęte, ale żaden z punktów zadania nie został kompletnie zrealizowany');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'czmaj'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'QA')), 3, 'Nie wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'czmaj'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Mobile (Android)')), 5, 'Wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'czmaj'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Mobile (Android)')), 2, 'Zadanie wykonane w połowie');

INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'serwerus'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Java')), 2, 'Zadanie wykonane w połowie');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'serwerus'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Java')), 3, 'Nie wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'serwerus'), (SELECT id FROM stage WHERE name = 'Etap III' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Java')), 0, 'Nie oddał zadania.');

INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'gdudek'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Java')), 4, 'Prawie wszystko wykonane poprawnie. Kod nie został prawidłowo sformatowany');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'gdudek'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Java')), 5, 'Wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'gdudek'), (SELECT id FROM stage WHERE name = 'Etap III' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'Java')), 4, 'Prawie wszystko wykonane poprawnie. Kod nie został prawidłowo sformatowany');

INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'waletyna'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'JavaScript')), 0, 'Nie oddał zadania.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'waletyna'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'JavaScript')), 3, 'Nie wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'waletyna'), (SELECT id FROM stage WHERE name = 'Etap III' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'JavaScript')), 5, 'Wszystko wykonane poprawnie.');

INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'jsina'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'JavaScript')), 4, 'Prawie wszystko wykonane poprawnie. Kod nie został prawidłowo sformatowany');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'jsina'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'JavaScript')), 3, 'Nie wszystko wykonane poprawnie.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'jsina'), (SELECT id FROM stage WHERE name = 'Etap III' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'JavaScript')), 2, 'Zadanie wykonane w połowie');

INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'emeryt'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'QA')), 4, 'Prawie wszystko wykonane poprawnie. Kod nie został prawidłowo sformatowany');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'emeryt'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'QA')), 3, 'Nie wszystko wykonane poprawnie.');

INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'pawlowska1'), (SELECT id FROM stage WHERE name = 'Etap I' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'QA')), 0, 'Nie oddał zadania.');
INSERT INTO user_stage(user_id, stage_id, mark, reason) VALUES((SELECT id FROM student_record.user WHERE login = 'pawlowska1'), (SELECT id FROM stage WHERE name = 'Etap II' and year = 2021 AND technology_group_id = (SELECT id FROM technology_group WHERE name = 'QA')), 1, 'Zadanie rozpoczęte, ale żaden z punktów zadania nie został kompletnie zrealizowany');